version: '3.9'
services:
  readme.notifications.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "readme.notifications.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "8025:8025"
      - "1083:8080"

  readme.notifications.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notifications.rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme.notifications.mongo:
    image: mongo:4.4
    container_name: readme.notifications.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-notifications

    ports:
      - 27020:27017

    volumes:
      - readme.notifications.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-notifications --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.notifications.mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.notifications.mongo.ui

    ports:
      - 8083:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.notifications.mongo:27017/

volumes:
  readme.notifications.mongo:
