version: '3.9'
services:
  readme.file-loader.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.file-loader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-file-loader

    ports:
      - 27018:27017

    volumes:
      - readme.mongo.file-loader:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-file-loader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.file-loader.mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.file-loader.mongo.ui
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.file-loader.mongo:27017/

volumes:
  readme.mongo.file-loader:
